const ROLES = {
  PATIENT: 'PATIENT',
  PROFESSIONAL: 'PROFESSIONAL',
  ADMIN: 'ADMIN',
  INSTITUTION: 'INSTITUTION'
};

const PERMISSIONS = {
  READ_PATIENT: 'read_patient',
  WRITE_PATIENT: 'write_patient',
  PRESCRIBE: 'prescribe',
  VIEW_AUDIT_LOGS: 'view_audit_logs'
};

const ROLE_PERMISSIONS = {
  [ROLES.PATIENT]: [],
  [ROLES.PROFESSIONAL]: [
    PERMISSIONS.READ_PATIENT,
    PERMISSIONS.WRITE_PATIENT,
    PERMISSIONS.PRESCRIBE
  ],
  [ROLES.ADMIN]: [
    PERMISSIONS.READ_PATIENT,
    PERMISSIONS.WRITE_PATIENT,
    PERMISSIONS.PRESCRIBE,
    PERMISSIONS.VIEW_AUDIT_LOGS
  ],
  [ROLES.INSTITUTION]: [PERMISSIONS.VIEW_AUDIT_LOGS]
};

function getPermissionsByRole(role) {
  return ROLE_PERMISSIONS[role] || [];
}

module.exports = {
  ROLES,
  PERMISSIONS,
  ROLE_PERMISSIONS,
  getPermissionsByRole
};
